"""
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

"""
import unittest

def fibonacci():
    sum_ = 0
    a = 0
    b = 1
    c = a + b
    while c < 4000000:
      if c%2 == 0:
        print(c)
        sum_ = sum_ + c
      a = b
      b = c
      c = a + b
    return sum_

solution = fibonacci()

print ('Solution: {}'.format(solution))

class Test_Euler_002(unittest.TestCase):
    def test_fibonacci(self):
        self.assertEqual(4613732, fibonacci())

unittest.main()